# Generated by Django 5.0 on 2024-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bulb funy', max_length=15, verbose_name='deco name')),
                ('type', models.CharField(choices=[('داخلية', 'داخلية'), ('خارجية', 'خارجية'), ('اكسسوار', 'اكسسوار')], default=('اكسسوار', 'اكسسوار'), max_length=13, verbose_name='النوع')),
                ('part_img', models.ImageField(default='car_part3.png', upload_to='decorators')),
                ('price', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='price(EGP)')),
                ('bio', models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True)),
                ('added_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Decorator_model',
                'verbose_name_plural': 'Decorator_model',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
