# Generated by Django 5.0 on 2024-05-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_decorator_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='has_deco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_decor', to='core.decorator_model'),
        ),
    ]
