# Generated by Django 5.0 on 2024-05-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_model_has_deco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petrol_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Petrojet EGY', max_length=30, null=True, verbose_name='petrol name')),
                ('f95', models.DecimalField(decimal_places=2, default=100.51, max_digits=10, verbose_name='f95 obtained(LE):')),
                ('f95_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f95 price(EGP)')),
                ('f92', models.DecimalField(decimal_places=2, default=25.2, max_digits=10, verbose_name='f92 obtained(LE):')),
                ('f92_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f92 price(EGP)')),
                ('f90', models.DecimalField(decimal_places=2, default=300.5, max_digits=10, verbose_name='f90 obtained(LE):')),
                ('f90_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f90 price(EGP)')),
                ('f80', models.DecimalField(decimal_places=2, default=50.6, max_digits=10, verbose_name='f80 obtained(LE):')),
                ('f80_cost', models.DecimalField(decimal_places=2, default=250, max_digits=10, verbose_name='f80 price(EGP)')),
            ],
            options={
                'verbose_name': 'Petrol_area',
                'verbose_name_plural': 'Petrol_area',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='school_of_drive',
            name='bio',
            field=models.TextField(blank=True, default='\nProvident nihil minus qui consequatur non omnis maiores. Eos accusantium minus dolores iure perferendis tempore et consequatur.\n                   \n', null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='has_school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_school', to='core.school_of_drive'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='profile_activity',
            field=models.CharField(choices=[('وكيل ماركة', 'وكيل ماركة'), ('مركز صيانة', 'مركز صيانة'), ('محل قطع غيار', 'محل قطع غيار'), ('إيجار', 'إيجار'), ('وقود', 'وقود'), ('شراء', 'شراء'), ('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), ('أكسسوارت', 'أكسسوارت'), ('مركز تدريب', 'مركز تدريب')], default=('بيع-إيجار-شراء', 'بيع-إيجار-شراء'), max_length=23, verbose_name='نوع النشاط'),
        ),
        migrations.AddField(
            model_name='user_model',
            name='has_petrol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_petrol', to='core.petrol_area'),
        ),
    ]
