# Generated by Django 5.0 on 2024-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_petrol_area_alter_school_of_drive_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='address',
            field=models.CharField(blank=True, default='م33محل الغربالي', max_length=40, null=True, verbose_name='العنوان'),
        ),
    ]
