# Generated by Django 5.0 on 2024-05-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_model_has_petrol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='has_petrol',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='has_school',
        ),
    ]
