# Generated by Django 5.0 on 2024-05-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_model_has_petrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='has_petrol',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_petrol', to='core.petrol_area'),
        ),
        migrations.AddField(
            model_name='user_model',
            name='has_school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_school', to='core.school_of_drive'),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='user_img',
            field=models.ImageField(default='car_part2.png', upload_to='<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
